[package]
name = "photo-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.5.0"
flate2 = "1.1.2"
image = { version = "0.25.6", default-feature = false, features = ["jpeg"] }
wasm-bindgen = "0.2.100"
